# ScriptEntityPlus v${project.version} Config #

## ===== オプションの置き換えの設定 ===== ##
# エンティティに実行させることで生じる不具合を防ぐために、
# 一部のオプションをエンティティ対応させた物に置き換える必要があります。
# (正常に動作している場合は、触らないでください。)
Replaces:
- '@delay:>>>@e_delay:'
- '@cooldown:>>>@e_cooldown:'
- '@oldcooldown:>>>@e_oldcooldown:'